---
version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/krogebry/.aws:/root/.aws
    environment:
      - PORT=8080
      - USE_AWS_CREDS=true
      - MISTY_ENV_NAME=dev
      - AWS_DEFAULT_REGION=us-east-1
